# Navigate to this directory and then run "mkdocs serve" to see a live-view of the documentation
# More settings: https://squidfunk.github.io/mkdocs-material/setup/

site_name: BeautifulEmail
site_description: BeautifulEmail is a python package that makes it easy and quick to send beautifully formatted emails with beuatiful tables/dataframes. BeautifulEmail is for Data Scientists with a deadline.
site_url: https://vanalmsi.github.io/beautifulemail/
theme:
  name: material
  favicon:
  icon:
    logo: material/email-edit-outline
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue green
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - search.suggest
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - navigation.top
    - navigation.footer

nav:
  - Home: "index.md"
  - Changelog & ToDos: "change_log.md"
  - Suggest an idea: "https://github.com/vanalmsick/beautifulemail/discussions/categories/ideas"


markdown_extensions:
  - def_list
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


plugins:
  - search
  - offline
  - mkdocstrings
#  - optimize
#  - render_swagger:
#      allow_arbitrary_locations: true

repo_url: https://github.com/vanalmsick/beautifulemail
repo_name: vanalmsick/beautifulemail
